// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------------- //
// halvoe_spi_peripheral //
// --------------------- //

#define halvoe_spi_peripheral_wrap_target 0
#define halvoe_spi_peripheral_wrap 2

static const uint16_t halvoe_spi_peripheral_program_instructions[] = {
            //     .wrap_target
    0x2021, //  0: wait   0 pin, 1                   
    0x20a1, //  1: wait   1 pin, 1                   
    0x4001, //  2: in     pins, 1                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program halvoe_spi_peripheral_program = {
    .instructions = halvoe_spi_peripheral_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config halvoe_spi_peripheral_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + halvoe_spi_peripheral_wrap_target, offset + halvoe_spi_peripheral_wrap);
    return c;
}
#endif

